### ISSUE TITLE
Newrelic Agent Version 6 Not supported 

### ISSUE THREAD

**Issue by gogovan-vincentngai** [yabeda-rb/yabeda-newrelic#1]
May be this project is already deprecated ?

Recently i find this plugin can be help inject data like thread and worker usage to newrelic ,

We did have try install this plugin which is working well work rails 5 + newrelic agent in 5.x 
however if we need upgrade rails to 6 in future and we must use newrelic agent 6.x 
rails 6 we must follow upgrade our newrelic agent to 6.x 

below are error when we try using 6.x + yabeda-newrelic

`Bundle complete! 87 Gemfile dependencies, 257 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
/usr/local/bundle/gems/newrelic_rpm-5.6.0.349/lib/new_relic/control/class_methods.rb:52:in `const_get': wrong constant name [[:warn, ["agent unavailable as it hasn't been started."], nil], [:warn, ["/usr/local/bundle/gems/newrelic_rpm-5.6.0.349/lib/new_relic/supportability_helper.rb:60:in `record_api_supportability_metric'\n/usr/local/bundle/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent.rb:416:in `add_instrumentation'\n/usr/local/bundle/gems/yabeda-newrelic-0.1.1/lib/yabeda/newrelic/adapter.rb:37:in `initialize'\n/usr/local/bundle/gems/yabeda-newrelic-0.1.1/lib/yabeda/newrelic/adapter.rb:60:in `new'\n/usr/local/bundle/gems/yabeda-newrelic-0.1.1/lib/yabeda/newrelic/adapter.rb:60:in `<class:adapter>'\n/usr/local/bundle/gems/yabeda-newrelic-0.1.1/lib/yabeda/newrelic/adapter.rb:10:in `<module:newrelic>'\n/usr/local/bundle/gems/yabeda-newrelic-0.1.1/lib/yabeda/newrelic/adapter.rb:7:in `<module:yabeda>'\n/usr/local/bundle/gems/yabeda-newrelic-0.1.1/lib/yabeda/newrelic/adapter.rb:6:in `<top (required)>'\n/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'\n/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'\n/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'\n/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'\n/usr/local/bundle/gems/yabeda-newrelic-0.1.1/lib/yabeda/newrelic.rb:5:in `<top (required)>'\n/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:95:in `require'\n/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:95:in `rescue in block in require'\n/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:72:in `block in require'\n/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:65:in `each'\n/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:65:in `require'\n/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:114:in `require'\n/app/config/application.rb:25:in `<top (required)>'\n/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'\n/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'\n/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'\n/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'\n/usr/local/bundle/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:141:in `block in perform'\n/usr/local/bundle/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `tap'\n/usr/local/bundle/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `perform'\n/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'\n/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'\n/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'\n/usr/local/bundle/gems/railties-6.0.3.2/lib/rails/command/base.rb:69:in `perform'\n/usr/local/bundle/gems/railties-6.0.3.2/lib/rails/command.rb:46:in `invoke'\n/usr/local/bundle/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<top (required)>'\n/app/bin/rails:9:in `require'\n/app/bin/rails:9:in `<top (required)>'\n/usr/local/bundle/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'\n/usr/local/bundle/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'\n/usr/local/bundle/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'\n/usr/local/bundle/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'\n/usr/local/bundle/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'\n/usr/local/bundle/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'\n/usr/local/bundle/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'\n/app/bin/spring:15:in `require'\n/app/bin/spring:15:in `<top (required)>'\nbin/rails:3:in `load'\nbin/rails:3:in `<main>'"], nil], [:error, ["detected unsupported rails version 6.0.3.2"], nil]] (NameError)
	from /usr/local/bundle/gems/newrelic_rpm-5.6.0.349/lib/new_relic/control/class_methods.rb:52:in `load_framework_class'
	from /usr/local/bundle/gems/newrelic_rpm-5.6.0.349/lib/new_relic/control/class_methods.rb:32:in `new_instance'
	from /usr/local/bundle/gems/newrelic_rpm-5.6.0.349/lib/new_relic/control/class_methods.rb:13:in `instance'`

**Comment by Envek** [comment]
We need to check whether any changes are needed for integration with NewRelic 6.

May be it is enough to just relax dependency version constraint in gemspec.

Thank you for reporting!

**Comment by Envek** [comment]
Checked it locally: it still works with latest version of newrelic_rpm (6.13.1 at the moment).

Please install version [0.2.0](https://rubygems.org/gems/yabeda-newrelic/versions/0.2.0) from rubygems.
